repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
    - id: codespell
      name: "Check code for common misspellings"
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.3
  hooks:
    - id: clang-format
      name: "C++ formatting"
      types_or: [c++, c, cuda, metal]
- repo: local
  hooks:
    - id: cppcheck
      name: "C++ static analysis"
      types_or: [c++, cuda, metal]
      entry: cppcheck -q -j8 --error-exitcode=1
      language: python
      additional_dependencies: ["cppcheck==1.5.1"]
      args:
        - --check-level=exhaustive
        - --language=c++
        - --enable=warning
        - -I include
        - program
        - src
        - test
        - test_package
